# Generated by Django 2.2.5 on 2019-10-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191005_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='core.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductStockLevel',
        ),
    ]
