# Generated by Django 2.2.5 on 2019-10-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productstocklevel_productsuppliers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSuppliers',
            new_name='ProductSupplier',
        ),
    ]
